# Generated by Django 5.2 on 2025-05-05 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log', '0003_child_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField()),
                ('suggestion', models.TextField()),
                ('insight', models.JSONField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.child')),
            ],
        ),
    ]
