# Generated by Django 5.2 on 2025-05-20 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.childprofile'),
        ),
    ]
