# Generated by Django 5.2 on 2025-05-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='parent',
        ),
    ]
