# Generated by Django 5.2 on 2025-05-20 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('log', '0003_child_parent'),
        ('report', '0002_alter_report_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartbeat',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='core.childprofile'),
        ),
        migrations.AlterField(
            model_name='scratchnotes',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scratch_notes', to='core.childprofile'),
        ),
        migrations.AlterField(
            model_name='behavior',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='core.childprofile'),
        ),
        migrations.AlterField(
            model_name='food',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='core.childprofile'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleeps', to='core.childprofile'),
        ),
        migrations.AlterField(
            model_name='bloodpressure',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_pressures', to='core.childprofile'),
        ),
        migrations.DeleteModel(
            name='Child',
        ),
    ]
